version: "3.9"

networks:
  timelogger-net:
    driver: bridge

services:

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: timelogger-front
    environment:
      - API_HOST=http://back:3000
    depends_on:
      - back
    volumes:
       - ./front:/home/node/front
       - /home/node/front/node_modules
    networks:
      - timelogger-net

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: timelogger-back
    ports:
      - "3000:3000"
    environment:
      - ENV=DEV
    networks:
      - timelogger-net
    volumes:
      - ./back/src:/home/node/back/src
      - /home/node/back/node_modules


  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: timelogger-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=workdb123
      - POSTGRES_DB=timelogger_db
    ports:
      - '5432:5432'
    networks:
      - timelogger-net
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: