version: "3.9"

networks:
  timelogger-net:
    driver: bridge

services:

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: timelogger-front
    depends_on:
      - back
    volumes:
       - ./front:/home/node/front
       - /home/node/front/node_modules
    networks:
      - timelogger-net

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: timelogger-back
    ports:
      - "3000:3000"
    environment:
      - ENV=DEV
    networks:
      - timelogger-net
    volumes:
      - ./src:/home/node/back/src
      - /home/node/back/node_modules
